openapi: 3.0.0

info:
  version: 1.0.0
  title: Quickstart
  description: Quickstart for OAS-Tools
  
servers:
- url: /api/v1
  description: Development server
  
paths:

  /word-counter:
    x-router-controller: wordController
    post:
      operationId: 'wordCounter'
      description: "counting words"
      requestBody:
        content:

          text/plain:
            schema:
              type: string

          # multipart/form-data:
          #   schema:
          #     type: string
          #     format: binary

          multipart/form-data:
            schema:
              type: object
              properties:
                # 'file' will be the field name in this multipart request
                file:
                  type: string
                  format: binary

          # image/png:
          #   schema:
          #     type: string
          #     format: binary
          
        # $ref: '#/components/requestBodies/WordCounterBody'
      responses:
        200:
          $ref: '#/components/responses/SuccessResponse'
        400:
          $ref: '#/components/responses/BadResponse'
        500:
          $ref: '#/components/responses/BadResponse'

  /word-statistics/{word}:
    x-router-controller: wordController
    get:
      operationId: 'wordStatistics'
      description: "word statistics"
      parameters:
        - in: path
          name: word
          schema:
            type: string
          required: true
          description: word for checking it's count
          
      responses:
        200:
          $ref: '#/components/responses/SuccessResponse'
        400:
          $ref: '#/components/responses/BadResponse'
        500:
          $ref: '#/components/responses/BadResponse'

  /all-word-statistics:
    x-router-controller: wordController
    get:
      operationId: 'allWordStatistics'
      description: "words statistics"
      
      responses:
        200:
          $ref: '#/components/responses/SuccessResponse'
        400:
          $ref: '#/components/responses/BadResponse'
        500:
          $ref: '#/components/responses/BadResponse'


components:
  # requestBodies:
  #   WordCounterBody:
  #     content:
  #       text/plain:
  #         schema:
  #           $ref: '#/components/schemas/StringBodySchema'
            
  responses:
    SuccessResponse:
      description: "OK"
    BadResponse:
      description: "KO"

  schemas:
    StringBodySchema:
      type: string

    

## edit with https://editor.swagger.io/